# -*- coding: utf-8 -*-
"""Pizza_Sipariş_Sistemi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r6ELMPWnPxHfGTX0FUNG06zNDZQ0tzsJ
"""

import decorator
from decorator import decorate
import csv
import datetime 

menu = open( "menu.txt" , "w" )
menu.write(" Lütfen Bir Pizza Tabanı Seçiniz: 1: Klasik , 2: Margarita , 3:TürkPizza , 4:Sade Pizza" )
menu.write("* ve seçeceğiniz sos: 11: Zeytin , 12: Mantarlar , 13: Keçi Peyniri , 14: Et , 15: Soğan, 16: Mısır , * Teşekkür ederiz! ")



#ÜST SINIF 
class Pizza:
    def __init__(self,description,cost):
        self.description = description
        self.cost = cost
      
    def get_description(self):
      return self.description
  
    def get_cost(self):
      return self.cost 




#ALT SINIF

class KlasikPizza(Pizza):

  def __init__(self):
        super().__init__('Klasik Pizza: Peynir, Zeytin , Domates' , 100.0 )

class MargaritaPizza(Pizza):

  def __init__(self):
        super().__init__('Margarita Pizza: Mozarella Peyniri , Fesleğen , domates' , 120.0 )

class TurkPizza(Pizza):

  def __init__(self):
        super().__init__('Türk Pizza: Kıyma , Maydanoz , Soğan' , 120.0 )


class KarisikPizza(Pizza):

  def __init__(self):
        super().__init__('Karışık Pizza: Cheddar Peyniri, Mantar , Salam, Sucuk, Domates ' , 150.0 )




#DECORATOR SINIFI

class Decorator(Pizza):     
    def __init__(self,component, description , cost):
        super().__init__(description , cost )
        self.component = component

    def get_description(self):
        return super().get_description() + ' ;' + self.component.get_description()

    def get_cost(self):
        return self.component.get_cost() + super().get_cost()

#SOSLAR - EK MALZEMELER

class Zeytin(Decorator):
    def __init__(self, component ):
        super().__init__(component , "zeytin" , 10.0 )
        

class  Mantar(Decorator):
    def __init__(self, component):
        super().__init__(component , "mantar" , 15.0 )
        

class KeciPeyniri(Decorator):
    def __init__(self, component):
        super().__init__(component , "Keçi Peyniri" , 20.0 )
        

class Et(Decorator):
    def __init__(self, component):
        super().__init__(component , "Et" , 30.0 )
        

class Sogan(Decorator):
    def __init__(self, component):
        super().__init__(component , "Soğan" , 7.0 )
        

class Misir(Decorator):
    def __init__(self, component):
        super().__init__(component , "Mısır" , 12.0 )
        

#MAIN FONKSİYONU

if __name__ == '__menu__': 
     menu()



#KULLANICININ PİZZA VE SOS SEÇİMLERİ
while True:
  
    pizza_tercihi = input("Lütfen Pizza tercihinizi yapınız: ")

    if pizza_tercihi == "1":
        pizza = KlasikPizza()
        break   
    elif pizza_tercihi == "2":
        pizza = MargaritaPizza()
        break
    elif pizza_tercihi == "3":
        pizza = TurkPizza()
        break
    elif pizza_tercihi == "4":
        pizza = KarisikPizza()
        break
    else:
        print("Lütfen geçerli bir tercih yapınız.")
        continue

while True:

      sos_tercihi = input("Lütfen sos tercihinizi yapınız.")

      if sos_tercihi == "11" :
          sos = Zeytin(pizza)
          break
      elif sos_tercihi == "12":
          sos = Mantar(pizza)
          break
      elif sos_tercihi == "13":
          sos = KeciPeyniri(pizza)
          break
      elif sos_tercihi == "14":
          sos = Et(pizza)
          break
      elif sos_tercihi == "15":
          sos = Sogan(pizza)
          break
      elif sos_tercihi == "16":
          sos = Misir(pizza)
          break
      else:
          print("Geçersiz tercih yaptınız. Lütfen tekrar deneyiniz.")
          continue

#SEÇİLEN ÜRÜNLERİN TOPLAM FİYATININ GETİRİLMESİ 

toplam_tutar = sos.get_cost()
print("Ödenecek Tutar: " , toplam_tutar ,"TL ")


while True: 
  
      siparis = input("Siparişiniz oluşturulmuştur. Ödeme ekranına geçmek için 1'e , siparişi sonlandırmak için 2'ye basınız.")

      if siparis == "1" :
          print("Ödeme ekranına yönlendiriliyorsunuz...")
          break

      elif siparis == "2":
          print("Siparişiniz sonlandırılmıştır.")
          break


#KULLANICI BİLGİLERİ , ÖDEME BÖLÜMÜ 
print("Not: Hatalı girilen bilgilerden kaynaklı sipariş sorunları işletmemizin sorumluluğunda değildir. :) Lütfen doğru bilgileri girdiğinizden emin olunuz. ")
isim = input("Lütfen adınızı ve soyadınızı giriniz:")
tc = input("Lütfen TC Kimlik numaranızı giriniz:")
kk = input("Lütfen Kredi Kartı numaranızı giriniz:")
ksifre = input("Lütfen Kredi Kartı şifrenizi giriniz:")

zaman = datetime.datetime.now()


with open("Orders_Database.csv", mode = "w", newline="", encoding='utf-8') as yeni_dosya:
        yazici = csv.writer(yeni_dosya, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        yazici.writerow([isim, tc, kk, ksifre, sos.get_description(), toplam_tutar, zaman])



print("Siparişiniz başarıyla oluşturulmuştur. Teşekkür ederiz.")